### ISSUE TITLE
오류

### ISSUE THREAD

**Issue by ghost** [sunghun7511/SahyangFarm#2]
이거 버전이 몇이에요?
그리고 다른 플러그인도 넣야하나요? 
이 플러그인 지정된 경로를 찾을 수 없대요...

**Comment by sunghun7511** [comment]
해당 플러그인은 1.12.2 기준으로 제작되었으며, [`libs` 폴더](https://github.com/sunghun7511/SahyangFarm/tree/master/libs) 내 `worldedit-bukkit-6.1.9.jar` 파일을 필요로 합니다.

저 또한 이 플러그인을 개발한지 너무 오래되어서 추가적인 도움을 드리기는 어렵습니다. 다만 기여하실 의향이 있으시다면 Pull Requests는 언제나 환영입니다. 감사합니다.
